name: SonarCloud Analysis

on:
  push:
    branches:
      - main  # Change to your default branch name if different
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from GitHub
      - uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Change this to your preferred Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # Install testing dependencies (optional)
          pip install pylint  # Install linter for code quality
          pip install flake8  # Install flake8 for additional linting checks
          pip install coverage  # Install coverage for code coverage analysis

      # Step 4: Run tests and generate coverage report
      - name: Run tests and generate coverage report
        run: |
          pytest --maxfail=1 --disable-warnings -q
          coverage run -m pytest
          coverage xml  # Generates the coverage.xml report

      # Step 5: Run SonarCloud analysis
      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Reference the token from GitHub secrets
        run: |
          sonar-scanner \
            -Dsonar.projectKey=Kavana179_Python-phonenumber-tracker-App \
            -Dsonar.organization=kavana179 \
            -Dsonar.sources=app.py  # Point to your source directory here (adjust path if needed)
            -Dsonar.language=python  # Explicitly set the language to Python
            -Dsonar.python.coverage.reportPaths=coverage.xml  # Path to the coverage report
            -Dsonar.python.version=3.9  # Set the exact Python version you're using
