name: SonarCloud Analysis

on:
  push:
    branches:
      - master  # Change this to your default branch name if it's not 'main'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from GitHub
      - uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # You can change this to your specific Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint  # Optional: install pylint to check code quality
          pip install flake8  # Optional: install flake8 for additional linting checks

      # Step 4: Run Pylint or Flake8 (Optional, for code linting)
      - name: Run Pylint or Flake8 (Optional)
        run: |
          pylint app.py  # Run pylint on app.py to get code quality issues (optional)
          flake8 app.py  # Run flake8 on app.py for additional checks (optional)

      # Step 5: Run SonarCloud analysis
      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Reference your SonarCloud token stored in GitHub secrets
        run: |
          sonar-scanner \
            -Dsonar.projectKey=Kavana179_Python-phonenumber-tracker-App \
            -Dsonar.organization=kavana179 \
            -Dsonar.sources=app.py  # Set this to the location of your Python file(s)
            -Dsonar.language=python  # Tell SonarCloud that you're analyzing Python code
            -Dsonar.python.version=3.9  # Set the exact Python version (same as the one in setup-python)
