name: SonarCloud Analysis

on:
  push:
    branches:
      - main  # Change to your default branch name if different
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from GitHub
      - uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Change this to your preferred Python version

      # Step 3: Install necessary dependencies manually
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # Install testing dependencies (optional)
          pip install pylint  # Install linter for code quality
          pip install flake8  # Install flake8 for additional linting checks
          pip install coverage  # Install coverage for code coverage analysis

      # Step 4: Run SonarCloud analysis
      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Reference the token from GitHub secrets
        run: |
          sonar-scanner \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.organization=your_organization_key \
            -Dsonar.sources=./src  # Specify the source directory for your Python project (usually ./src or .)
